<?xml version="1.0" encoding="UTF-8"?>
<Worksheet>
<Version major="2020" minor="0"/>
<Label-Scheme value="2" prefix=""/>
<View-Properties presentation="false" autoexpanding_sections="true" UserProfileName="Maple Default Profile" NumericFormat-ApplyInteger="true" NumericFormat-ApplyRational="true" NumericFormat-ApplyExponent="false" editable="true">
</View-Properties>
<MapleNet-Properties prettyprint="3" warnlevel="3" compactdisplay="false" preplot="" helpbrowser="standard" displayprecision="-1" echo="1" unitattributes="&quot;fontweight&quot; = &quot;bold&quot;" imaginaryunit="I" longdelim="true" elisiontermsthreshold="10000" elisiondigitsafter="100" elisiondigitsbefore="100" plotdevice="inline" errorbreak="1" plotoptions="" plotdriver="opengl" quiet="false" elisiontermsbefore="100" elisiontermsafter="100" historytimestamp="false" screenwidth="79" indentamount="4" plotoutput="terminal" screenpixelheight="1824" rtablesize="[10, 10]" useclientjvm="true" labelwidth="20" postplot="" typesetting="extended" ansi="false" ansicolor="[]" elisiondigitsthreshold="10000" showassumed="1" ansilprint="false" trailingsemicolon="true" errorcursor="false" labelling="true" screenheight="25" prompt="&gt; " verboseproc="1" latexwidth="8.0" ShowLabels="true"/>
<Styles>
<Font name="Heading 1" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Warning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Line Printed Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 2" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="16" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Inert Output" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[144,144,144]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 3" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="14" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Diagnostic" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[40,120,40]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 1" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[120,0,14]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 2" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 3" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 5" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Header and Footer" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="10" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkError" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Atomic Variable" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[175,0,175]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkWarning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Dictionary Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[147,0,15]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="2D Math" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Bullet Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Plot" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="List Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Dash Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Input" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Error" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Normal" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Caption Reference" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Code" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input Placeholder" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[200,0,200]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="true"/>
<Font name="Equation Label" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Author" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,128,128]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Caption Text" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Layout name="Heading 1" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="4" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Warning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 4" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Line Printed Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 2" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="2" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Output" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.3" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 3" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Diagnostic" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 1" alignment="left" bullet="numeric" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Text Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="newline" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 2" alignment="left" bullet="alphabetic" firstindent="0" leftmargin="36" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 3" alignment="left" bullet="roman" firstindent="0" leftmargin="72" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 4" alignment="left" bullet="ALPHABETIC" firstindent="0" leftmargin="108" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 5" alignment="left" bullet="ROMAN" firstindent="0" leftmargin="144" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Annotation Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkError" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkWarning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Bullet Item" alignment="left" bullet="dot" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Plot" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="List Item" alignment="left" bullet="indent" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Dash Item" alignment="left" bullet="dash" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Error" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Normal" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Author" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="8" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Pencil-style name="Pencil 1" pen-color="[0,0,0]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 2" pen-color="[0,0,255]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 3" pen-color="[0,0,0]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 4" pen-color="[0,0,255]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 5" pen-color="[255,0,0]" pen-height="5.0" pen-width="5.0" pen-opacity="1.0"/>
<Highlighter-style name="Highlighter 5" pen-color="[255,255,0]" pen-height="48.0" pen-width="48.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 3" pen-color="[51,255,0]" pen-height="24.0" pen-width="24.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 4" pen-color="[0,255,255]" pen-height="32.0" pen-width="32.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 1" pen-color="[255,153,255]" pen-height="12.0" pen-width="8.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 2" pen-color="[255,204,0]" pen-height="14.0" pen-width="14.0" pen-opacity="0.8"/>
</Styles>
<Startup-Code startupcode=""/>
<Task-table>
    <Task-category name="&lt;default&gt;"/>
</Task-table>
<Task/>
<Group hide-input="false" labelreference="L2" drawlabel="true" applyint="true" applyrational="true" applyexponent="false"><Text-field prompt="&gt; " style="Maple Input" layout="Normal">ans := -1/(-(-RootOf(_Z^3*t^3-_Z^2*t^3+(t^2-1)*_Z+1)+1)/RootOf(_Z^3*t^3-_Z^2*t^</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">3+(t^2-1)*_Z+1)+t^3*RootOf(_Z^3*t^3-_Z^2*t^3+(t^2-1)*_Z+1)^2-1);</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">ans_latex_code := &quot;- \134\134left( -{\134\134frac {-{\134\134it RootOf} \134\134left( {{\134\134it \134\134_Z}}^{3}\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">{t}^{3}-{{\134\134it \134\134_Z}}^{2}{t}^{3}+ \134\134left( {t}^{2}-1 \134\134right) {\134\134it \134\134_Z}+1 \134\134ri\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">ght) +1}{{\134\134it RootOf} \134\134left( {{\134\134it \134\134_Z}}^{3}{t}^{3}-{{\134\134it \134\134_Z}}^{2}{t}^{3\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">}+ \134\134left( {t}^{2}-1 \134\134right) {\134\134it \134\134_Z}+1 \134\134right) }}+{t}^{3} \134\134left( {\134\134it R\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">ootOf} \134\134left( {{\134\134it \134\134_Z}}^{3}{t}^{3}-{{\134\134it \134\134_Z}}^{2}{t}^{3}+ \134\134left( {t}^{\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">2}-1 \134\134right) {\134\134it \134\134_Z}+1 \134\134right)  \134\134right) ^{2}-1 \134\134right) ^{-1}&quot;;</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Font encoding="UTF-8">T := series(1+1*t^2+1*t^3+1*t^4+5*t^5+2*t^6+14*t^7+13*t^8+31*t^9+66*t^10+77*t^1\134</Font></Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">1+240*t^12+286*t^13+722*t^14+1226*t^15+2141*t^16+4760*t^17+7268*t^18+16473*t^19</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">+O(t^20),t,20);</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">P := 16473*t^19+7268*t^18+4760*t^17+2141*t^16+1226*t^15+722*t^14+286*t^13+240*t</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">^12+77*t^11+66*t^10+31*t^9+13*t^8+14*t^7+2*t^6+5*t^5+t^4+t^3+t^2+1;</Text-field>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYnLUkjbWlHRiQ2J1EkYW5zRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLyUqcmVmZXJlbmNlR1ElMzEzNkYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSUzMTM1RictSSNtb0dGJDYvUSkmQXNzaWduO0YnL0YzUSdub3JtYWxGJ0Y1RjgvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRkMvJSlzdHJldGNoeUdGQy8lKnN5bW1ldHJpY0dGQy8lKGxhcmdlb3BHRkMvJS5tb3ZhYmxlbGltaXRzR0ZDLyUnYWNjZW50R0ZDLyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGUi1GPDYvUSomdW1pbnVzMDtGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZOL0ZRUSwwLjIyMjIyMjJlbUYnL0ZURlktSSZtZnJhY0dGJDYoLUkjbW5HRiQ2JlEiMUYnRj9GNUY4LUYjNilGVS1GZm42KC1GIzYnRlUtRiM2Ji1GLDYnUSdSb290T2ZGJ0YvRjJGNUY4LUY8Ni9RMCZBcHBseUZ1bmN0aW9uO0YnRj9GNUY4RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGW3AtSShtZmVuY2VkR0YkNiYtRiM2Ki1GIzYmLUklbXN1cEdGJDYlLUYsNidRI19aRidGL0YyRjVGOC1GaW42JlEiM0YnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJy1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZqb0ZccC1GZXA2JS1GLDYnUSJ0RidGL0YyRjVGOEZqcEZdcUY/LUY8Ni9RKCZtaW51cztGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZORlhGWi1GIzYmLUZlcDYlRmdwLUZpbjYmUSIyRidGP0Y1RjhGXXFGYHFGY3FGPy1GPDYvUScmcGx1cztGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZORlhGWi1GIzYmLUZecDYmLUYjNiYtRmVwNiVGZXFGX3JGXXFGaHFGaG5GP0Y/RjVGOEZgcUZncEY/RmJyRmhuRj9GP0Y1RjhGP0ZickZobkY/RmJvLyUubGluZXRoaWNrbmVzc0dGW28vJStkZW5vbWFsaWduR1EnY2VudGVyRicvJSludW1hbGlnbkdGYXMvJSliZXZlbGxlZEdGQ0Zici1GIzYmRmNxRmBxLUZlcDYlRmJvRl9yRl1xRj9GaHFGaG5GP0Zdc0Zfc0Zic0Zkc0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSRhbnNHRigsJCokLCgqJiwmLUknUm9vdE9mR0YlNiMsKiomSSNfWkdGJSIiJEkidEdGKEY5IiIiKiZGOCIiI0Y6RjkhIiIqJiwmKiRGOkY9RjtGPkY7RjtGOEY7RjtGO0Y7Rj5GO0Y7RjtGM0Y+Rj4qJkY6RjlGM0Y9RjtGPkY7Rj5GPjcjRi4=</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbWlHRiQ2J1EvYW5zX2xhdGV4X2NvZGVGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRicvJSpyZWZlcmVuY2VHUSUzMTM2RicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTMxMzVGJy1JI21vR0YkNi9RKSZBc3NpZ247RicvRjNRJ25vcm1hbEYnRjVGOC8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGQy8lKXN0cmV0Y2h5R0ZDLyUqc3ltbWV0cmljR0ZDLyUobGFyZ2VvcEdGQy8lLm1vdmFibGVsaW1pdHNHRkMvJSdhY2NlbnRHRkMvJSdsc3BhY2VHUSwwLjI3Nzc3NzhlbUYnLyUncnNwYWNlR0ZSLUkjbXNHRiQ2I1FhZGwtflxsZWZ0KH4tfGZyXGZyYWN+fGZyLXxmclxpdH5Sb290T2Z8aHJ+XGxlZnQofnxmcnxmclxpdH5cX1p8aHJ8aHJefGZyM3xocnxmcnR8aHJefGZyM3xoci18ZnJ8ZnJcaXR+XF9afGhyfGhyXnxmcjJ8aHJ8ZnJ0fGhyXnxmcjN8aHIrflxsZWZ0KH58ZnJ0fGhyXnxmcjJ8aHItMX5ccmlnaHQpfnxmclxpdH5cX1p8aHIrMX5ccmlnaHQpfisxfGhyfGZyfGZyXGl0flJvb3RPZnxocn5cbGVmdCh+fGZyfGZyXGl0flxfWnxocnxocl58ZnIzfGhyfGZydHxocl58ZnIzfGhyLXxmcnxmclxpdH5cX1p8aHJ8aHJefGZyMnxocnxmcnR8aHJefGZyM3xocit+XGxlZnQofnxmcnR8aHJefGZyMnxoci0xflxyaWdodCl+fGZyXGl0flxfWnxocisxflxyaWdodCl+fGhyfGhyK3xmcnR8aHJefGZyM3xocn5cbGVmdCh+fGZyXGl0flJvb3RPZnxocn5cbGVmdCh+fGZyfGZyXGl0flxfWnxocnxocl58ZnIzfGhyfGZydHxocl58ZnIzfGhyLXxmcnxmclxpdH5cX1p8aHJ8aHJefGZyMnxocnxmcnR8aHJefGZyM3xocit+XGxlZnQofnxmcnR8aHJefGZyMnxoci0xflxyaWdodCl+fGZyXGl0flxfWnxocisxflxyaWdodCl+flxyaWdodCl+XnxmcjJ8aHItMX5ccmlnaHQpfl58ZnItMXxockYnRj8=">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SS9hbnNfbGF0ZXhfY29kZUdGKFFhZGwtflxsZWZ0KH4tfGZyXGZyYWN+fGZyLXxmclxpdH5Sb290T2Z8aHJ+XGxlZnQofnxmcnxmclxpdH5cX1p8aHJ8aHJefGZyM3xocnxmcnR8aHJefGZyM3xoci18ZnJ8ZnJcaXR+XF9afGhyfGhyXnxmcjJ8aHJ8ZnJ0fGhyXnxmcjN8aHIrflxsZWZ0KH58ZnJ0fGhyXnxmcjJ8aHItMX5ccmlnaHQpfnxmclxpdH5cX1p8aHIrMX5ccmlnaHQpfisxfGhyfGZyfGZyXGl0flJvb3RPZnxocn5cbGVmdCh+fGZyfGZyXGl0flxfWnxocnxocl58ZnIzfGhyfGZydHxocl58ZnIzfGhyLXxmcnxmclxpdH5cX1p8aHJ8aHJefGZyMnxocnxmcnR8aHJefGZyM3xocit+XGxlZnQofnxmcnR8aHJefGZyMnxoci0xflxyaWdodCl+fGZyXGl0flxfWnxocisxflxyaWdodCl+fGhyfGhyK3xmcnR8aHJefGZyM3xocn5cbGVmdCh+fGZyXGl0flJvb3RPZnxocn5cbGVmdCh+fGZyfGZyXGl0flxfWnxocnxocl58ZnIzfGhyfGZydHxocl58ZnIzfGhyLXxmcnxmclxpdH5cX1p8aHJ8aHJefGZyMnxocnxmcnR8aHJefGZyM3xocit+XGxlZnQofnxmcnR8aHJefGZyMnxoci0xflxyaWdodCl+fGZyXGl0flxfWnxocisxflxyaWdodCl+flxyaWdodCl+XnxmcjJ8aHItMX5ccmlnaHQpfl58ZnItMXxockYoNyNGLg==</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzZMLUkjbWlHRiQ2J1EiVEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTMxMzZGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMzEzNUYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZnbi1JJW1zdXBHRiQ2JS1GLDYnUSJ0RidGL0YyRjVGOC1GVjYmUSIyRidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnRlktRmpuNiVGXG8tRlY2JlEiM0YnRj9GNUY4RmJvRlktRmpuNiVGXG8tRlY2JlEiNEYnRj9GNUY4RmJvRlktRiM2Ji1GVjYmUSI1RidGP0Y1RjgtRjw2L1ExJkludmlzaWJsZVRpbWVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGaHAtRmpuNiVGXG9GYXBGYm9GP0ZZLUYjNiZGX29GZHAtRmpuNiVGXG8tRlY2JlEiNkYnRj9GNUY4RmJvRj9GWS1GIzYmLUZWNiZRIzE0RidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEiN0YnRj9GNUY4RmJvRj9GWS1GIzYmLUZWNiZRIzEzRidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEiOEYnRj9GNUY4RmJvRj9GWS1GIzYmLUZWNiZRIzMxRidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEiOUYnRj9GNUY4RmJvRj9GWS1GIzYmLUZWNiZRIzY2RidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMTBGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSM3N0YnRj9GNUY4RmRwLUZqbjYlRlxvLUZWNiZRIzExRidGP0Y1RjhGYm9GP0ZZLUYjNiYtRlY2JlEkMjQwRidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMTJGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSQyODZGJ0Y/RjVGOEZkcC1Gam42JUZcb0ZfckZib0Y/RlktRiM2Ji1GVjYmUSQ3MjJGJ0Y/RjVGOEZkcC1Gam42JUZcb0ZlcUZib0Y/RlktRiM2Ji1GVjYmUSUxMjI2RidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMTVGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSUyMTQxRidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMTZGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSU0NzYwRidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMTdGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSU3MjY4RidGP0Y1RjhGZHAtRmpuNiVGXG8tRlY2JlEjMThGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSYxNjQ3M0YnRj9GNUY4RmRwLUZqbjYlRlxvLUZWNiZRIzE5RidGP0Y1RjhGYm9GP0ZZLUYjNiYtRjw2L1EiT0YnRj9GNUY4RkFGREZGRkhGSkZMRk5GZ3BGaXAtRjw2L1EwJkFwcGx5RnVuY3Rpb247RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZncEZpcC1JKG1mZW5jZWRHRiQ2Ji1GIzYmLUZqbjYlRlxvLUZWNiZRIzIwRidGP0Y1RjhGYm8vJStmb3JlZ3JvdW5kR1EoWzAsMCwwXUYnLyUpcmVhZG9ubHlHRkNGP0Y/RjVGOEY/Rj8=">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJUR0YoK0tJInRHRigiIiIiIiFGMCIiI0YwIiIkRjAiIiUiIiZGNUYyIiInIiM5IiIoIiM4IiIpIiNKIiIqIiNtIiM1IiN4IiM2IiRTIyIjNyIkJ0dGOSIkQShGNyIlRTciIzoiJVRAIiM7IiVnWiIjPCIlb3MiIz0iJnRrIiIjPi1JIk9HRiU2I0YwIiM/NyNGLg==</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzZKLUkjbWlHRiQ2J1EiUEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTMxMzZGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMzEzNUYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiM2Ji1JI21uR0YkNiZRJjE2NDczRidGP0Y1RjgtRjw2L1ExJkludmlzaWJsZVRpbWVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGaW4tSSVtc3VwR0YkNiUtRiw2J1EidEYnRi9GMkY1RjgtRlg2JlEjMTlGJ0Y/RjVGOC8lMXN1cGVyc2NyaXB0c2hpZnRHUSIwRidGPy1GPDYvUScmcGx1cztGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZOL0ZRUSwwLjIyMjIyMjJlbUYnL0ZURltwLUYjNiYtRlg2JlElNzI2OEYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIzE4RidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRJTQ3NjBGJ0Y/RjVGOEZlbi1GXG82JUZeby1GWDYmUSMxN0YnRj9GNUY4RmRvRj9GZ28tRiM2Ji1GWDYmUSUyMTQxRidGP0Y1RjhGZW4tRlxvNiVGXm8tRlg2JlEjMTZGJ0Y/RjVGOEZkb0Y/RmdvLUYjNiYtRlg2JlElMTIyNkYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIzE1RidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRJDcyMkYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIzE0RidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRJDI4NkYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIzEzRidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRJDI0MEYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIzEyRidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRIzc3RidGP0Y1RjhGZW4tRlxvNiVGXm8tRlg2JlEjMTFGJ0Y/RjVGOEZkb0Y/RmdvLUYjNiYtRlg2JlEjNjZGJ0Y/RjVGOEZlbi1GXG82JUZeby1GWDYmUSMxMEYnRj9GNUY4RmRvRj9GZ28tRiM2Ji1GWDYmUSMzMUYnRj9GNUY4RmVuLUZcbzYlRl5vLUZYNiZRIjlGJ0Y/RjVGOEZkb0Y/RmdvLUYjNiZGZnNGZW4tRlxvNiVGXm8tRlg2JlEiOEYnRj9GNUY4RmRvRj9GZ28tRiM2JkZcc0Zlbi1GXG82JUZeby1GWDYmUSI3RidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRIjJGJ0Y/RjVGOEZlbi1GXG82JUZeby1GWDYmUSI2RidGP0Y1RjhGZG9GP0Znby1GIzYmLUZYNiZRIjVGJ0Y/RjVGOEZlbi1GXG82JUZeb0ZbeEZkb0Y/RmdvLUZcbzYlRl5vLUZYNiZRIjRGJ0Y/RjVGOEZkb0Znby1GXG82JUZeby1GWDYmUSIzRidGP0Y1RjhGZG9GZ28tRlxvNiVGXm9GYXdGZG9GZ28tRlg2JlEiMUYnRj9GNUY4Rj8=">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJQR0YoLEgqJEkidEdGKCIjPiImdGsiKiRGMCIjPSIlb3MqJEYwIiM8IiVnWiokRjAiIzsiJVRAKiRGMCIjOiIlRTcqJEYwIiM5IiRBKCokRjAiIzgiJCdHKiRGMCIjNyIkUyMqJEYwIiM2IiN4KiRGMCIjNSIjbSokRjAiIioiI0oqJEYwIiIpRkMqJEYwIiIoRkAqJEYwIiInIiIjKiRGMCIiJkZZKiRGMCIiJSIiIiokRjAiIiRGZm4qJEYwRldGZm5GZm5GZm43I0Yu</Equation></Text-field>
</Output>
</Group>
<Group hide-input="false" labelreference="L19" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYpLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy1JI21vR0YkNi9RKiZjb2xvbmVxO0YnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiw2JVEmZXZhbGFGJ0YvRjItSShtZmVuY2VkR0YkNiYtRiM2JS1GLDYlUShNaW5wb2x5RidGL0YyLUZZNiYtRiM2Ji1GLDYlUSRhbnNGJ0YvRjItRjY2L1EiLEYnRjlGO0Y+RkEvRkVGMUZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRRLDAuMzMzMzMzM2VtRictRiw2JVEiekYnRi9GMkY5RjlGO0Y+RjlGOUY7Rj4tRjY2L1EiOkYnRjlGO0Y+RkFGREZGRkhGSkZMRk5GUEZTLyUrZXhlY3V0YWJsZUdGQ0Y5">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYpLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy1JI21vR0YkNi9RKiZjb2xvbmVxO0YnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiw2JVEmZXZhbGFGJ0YvRjItSShtZmVuY2VkR0YkNiYtRiM2JS1GLDYlUShNaW5wb2x5RidGL0YyLUZZNiYtRiM2Ji1GLDYlUSRhbnNGJ0YvRjItRjY2L1EiLEYnRjlGO0Y+RkEvRkVGMUZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRRLDAuMzMzMzMzM2VtRictRiw2JVEiekYnRi9GMkY5RjlGO0Y+RjlGOUY7Rj4tRjY2L1EiOkYnRjlGO0Y+RkFGREZGRkhGSkZMRk5GUEZTLyUrZXhlY3V0YWJsZUdGQ0Y5</Equation></Text-field>
</Input>
</Group>
<Group hide-input="false" labelreference="L20" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYpLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy1JI21vR0YkNi9RKiZjb2xvbmVxO0YnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiw2JVElc29ydEYnRi9GMi1JKG1mZW5jZWRHRiQ2Ji1GIzYrLUYsNiVRKXNpbXBsaWZ5RidGL0YyLUZZNiYtRiM2KEYrLUY2Ni9RJyZzZG90O0YnRjlGO0Y+RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGYm8tRiw2JVEmZGVub21GJ0YvRjItRlk2Ji1GIzYlRisvJStleGVjdXRhYmxlR0ZDRjlGOUY7Rj5GW3BGOUY5RjtGPi1GNjYvUSIsRidGOUY7Rj5GQS9GRUYxRkZGSEZKRkxGTkZhby9GVFEsMC4zMzMzMzMzZW1GJy1GLDYlUSJ6RidGL0YyRl1wLUY2Ni9RIn5GJ0Y5RjtGPkZBRkRGRkZIRkpGTEZORmFvRmNvLUYsNiVRKmFzY2VuZGluZ0YnRi9GMkZbcEY5RjlGO0Y+LUY2Ni9RIjpGJ0Y5RjtGPkZBRkRGRkZIRkpGTEZORlBGU0ZbcEY5">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYpLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy1JI21vR0YkNi9RKiZjb2xvbmVxO0YnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiw2JVElc29ydEYnRi9GMi1JKG1mZW5jZWRHRiQ2Ji1GIzYrLUYsNiVRKXNpbXBsaWZ5RidGL0YyLUZZNiYtRiM2KEYrLUY2Ni9RJyZzZG90O0YnRjlGO0Y+RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGYm8tRiw2JVEmZGVub21GJ0YvRjItRlk2Ji1GIzYlRisvJStleGVjdXRhYmxlR0ZDRjlGOUY7Rj5GW3BGOUY5RjtGPi1GNjYvUSIsRidGOUY7Rj5GQS9GRUYxRkZGSEZKRkxGTkZhby9GVFEsMC4zMzMzMzMzZW1GJy1GLDYlUSJ6RidGL0YyRl1wLUY2Ni9RIn5GJ0Y5RjtGPkZBRkRGRkZIRkpGTEZORmFvRmNvLUYsNiVRKmFzY2VuZGluZ0YnRi9GMkZbcEY5RjlGO0Y+LUY2Ni9RIjpGJ0Y5RjtGPkZBRkRGRkZIRkpGTEZORlBGU0ZbcEY5</Equation></Text-field>
</Input>
</Group>
<Group hide-input="false" labelreference="L21" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYlLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lK2V4ZWN1dGFibGVHUSZmYWxzZUYnL0YzUSdub3JtYWxGJw==">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYlLUkjbWlHRiQ2JVEiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lK2V4ZWN1dGFibGVHUSZmYWxzZUYnL0YzUSdub3JtYWxGJw==</Equation></Text-field>
</Input>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYqLUkjbW5HRiQ2JlEiMUYnLyUsbWF0aHZhcmlhbnRHUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTMxMzZGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMzEzNUYnLUkjbW9HRiQ2L1EnJnBsdXM7RidGL0YyRjUvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRj4vJSlzdHJldGNoeUdGPi8lKnN5bW1ldHJpY0dGPi8lKGxhcmdlb3BHRj4vJS5tb3ZhYmxlbGltaXRzR0Y+LyUnYWNjZW50R0Y+LyUnbHNwYWNlR1EsMC4yMjIyMjIyZW1GJy8lJ3JzcGFjZUdGTS1GIzYmLUkobWZlbmNlZEdGJDYmLUYjNigtSSVtc3VwR0YkNiUtSSNtaUdGJDYnUSJ0RicvJSdpdGFsaWNHUSV0cnVlRicvRjBRJ2l0YWxpY0YnRjJGNS1GLDYmUSIzRidGL0YyRjUvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnLUY5Ni9RKCZtaW51cztGJ0YvRjJGNUY8Rj9GQUZDRkVGR0ZJRktGTi1GWDYlRlotRiw2JlEiMkYnRi9GMkY1RmBvRjhGK0YvRi9GMkY1LUY5Ni9RMSZJbnZpc2libGVUaW1lcztGJ0YvRjJGNUY8Rj9GQUZDRkVGR0ZJL0ZMUSYwLjBlbUYnL0ZPRl9wLUZlbjYnUSJ6RidGaG5GW29GMkY1Ri9GOC1GIzYmLUZTNiYtRiM2LC1GWDYlRlotRiw2JlEiNUYnRi9GMkY1RmBvRmNvLUZYNiVGWi1GLDYmUSI0RidGL0YyRjVGYG9GOEZXRjgtRiM2JkZob0ZbcEZmb0YvRmNvRitGL0YvRjJGNUZbcC1GWDYlRmFwRmhvRmBvRi9GOC1GIzYmLUZTNiYtRiM2LC1GIzYmLUYsNiZRIjZGJ0YvRjJGNUZbcEZqcEYvRmNvLUYjNiZGXW9GW3BGX3FGL0Y4LUYjNiZGaG9GW3BGV0YvRjgtRiM2JkZdb0ZbcEZmb0YvRmNvRitGL0YvRjJGNUZbcC1GWDYlRmFwRl1vRmBvRi9GLw==">LCoiIiJGIyomLCgqJEkidEc2IiIiJEYjKiRGJyIiIyEiIkYjRiNGI0kiekdGKEYjRiMqJiwsKiRGJyIiJkYjKiRGJyIiJUYsRiZGI0YqRitGLEYjRiNGLUYrRiMqJiwsRjAiIidGMiEiJEYmRitGKkYpRixGI0YjRi1GKUYj</Equation></Text-field>
</Output>
</Group>
<Group labelreference="L3" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYlLUkjbWlHRiQ2I1EhRicvJStleGVjdXRhYmxlR1EmZmFsc2VGJy8lLG1hdGh2YXJpYW50R1Enbm9ybWFsRic=">JSFH</Equation></Text-field>
</Input>
</Group>
</Worksheet>