<?xml version="1.0" encoding="UTF-8"?>
<Worksheet>
<Version major="2020" minor="0"/>
<Label-Scheme value="2" prefix=""/>
<View-Properties presentation="false" autoexpanding_sections="true" UserProfileName="Maple Default Profile" NumericFormat-ApplyInteger="true" NumericFormat-ApplyRational="true" NumericFormat-ApplyExponent="false" editable="true">
</View-Properties>
<MapleNet-Properties prettyprint="3" warnlevel="3" compactdisplay="false" preplot="" helpbrowser="standard" displayprecision="-1" echo="1" unitattributes="&quot;fontweight&quot; = &quot;bold&quot;" imaginaryunit="I" longdelim="true" elisiontermsthreshold="10000" elisiondigitsafter="100" elisiondigitsbefore="100" plotdevice="inline" errorbreak="1" plotoptions="" plotdriver="opengl" quiet="false" elisiontermsbefore="100" elisiontermsafter="100" historytimestamp="false" screenwidth="79" indentamount="4" plotoutput="terminal" screenpixelheight="1824" rtablesize="[10, 10]" useclientjvm="true" labelwidth="20" postplot="" typesetting="extended" ansi="false" ansicolor="[]" elisiondigitsthreshold="10000" showassumed="1" ansilprint="false" trailingsemicolon="true" errorcursor="false" labelling="true" screenheight="25" prompt="&gt; " verboseproc="1" latexwidth="8.0" ShowLabels="true"/>
<Styles>
<Font name="Heading 1" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Warning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Line Printed Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 2" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="16" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Inert Output" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[144,144,144]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 3" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="14" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Diagnostic" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[40,120,40]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 1" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[120,0,14]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 2" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 3" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 5" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Header and Footer" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="10" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkError" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Atomic Variable" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[175,0,175]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkWarning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Dictionary Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[147,0,15]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="2D Math" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Bullet Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Plot" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="List Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Dash Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Input" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Error" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Normal" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Caption Reference" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Code" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input Placeholder" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[200,0,200]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="true"/>
<Font name="Equation Label" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Author" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,128,128]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Caption Text" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Layout name="Heading 1" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="4" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Warning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 4" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Line Printed Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 2" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="2" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Output" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.3" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 3" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Diagnostic" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 1" alignment="left" bullet="numeric" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Text Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="newline" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 2" alignment="left" bullet="alphabetic" firstindent="0" leftmargin="36" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 3" alignment="left" bullet="roman" firstindent="0" leftmargin="72" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 4" alignment="left" bullet="ALPHABETIC" firstindent="0" leftmargin="108" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 5" alignment="left" bullet="ROMAN" firstindent="0" leftmargin="144" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Annotation Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkError" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkWarning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Bullet Item" alignment="left" bullet="dot" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Plot" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="List Item" alignment="left" bullet="indent" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Dash Item" alignment="left" bullet="dash" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Error" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Normal" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Author" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="8" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Pencil-style name="Pencil 1" pen-color="[0,0,0]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 2" pen-color="[0,0,255]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 3" pen-color="[0,0,0]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 4" pen-color="[0,0,255]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 5" pen-color="[255,0,0]" pen-height="5.0" pen-width="5.0" pen-opacity="1.0"/>
<Highlighter-style name="Highlighter 5" pen-color="[255,255,0]" pen-height="48.0" pen-width="48.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 3" pen-color="[51,255,0]" pen-height="24.0" pen-width="24.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 4" pen-color="[0,255,255]" pen-height="32.0" pen-width="32.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 1" pen-color="[255,153,255]" pen-height="12.0" pen-width="8.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 2" pen-color="[255,204,0]" pen-height="14.0" pen-width="14.0" pen-opacity="0.8"/>
</Styles>
<Startup-Code startupcode=""/>
<Task-table>
    <Task-category name="&lt;default&gt;"/>
</Task-table>
<Task/>
<Group hide-input="false" labelreference="L2" drawlabel="true" applyint="true" applyrational="true" applyexponent="false"><Text-field prompt="&gt; " style="Maple Input" layout="Normal">ans := -(RootOf(t^4*_Z^4-t^4*_Z^3+(t^2-1)*_Z+1)^2-RootOf(t^4*_Z^4-t^4*_Z^3+(t^2</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">-1)*_Z+1))/(-((t^4-t^2)*RootOf(t^4*_Z^4-t^4*_Z^3+(t^2-1)*_Z+1)^3+RootOf(t^4*_Z^</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">4-t^4*_Z^3+(t^2-1)*_Z+1)^2*t^2)*(-RootOf(t^4*_Z^4-t^4*_Z^3+(t^2-1)*_Z+1)+1)/</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">RootOf(t^4*_Z^4-t^4*_Z^3+(t^2-1)*_Z+1)/t^2+1+(-t^2+1)*RootOf(t^4*_Z^4-t^4*_Z^3+</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">(t^2-1)*_Z+1)^3-RootOf(t^4*_Z^4-t^4*_Z^3+(t^2-1)*_Z+1)^2-RootOf(t^4*_Z^4-t^4*_Z</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">^3+(t^2-1)*_Z+1));</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">T := series(1+1*t^2+2*t^4+7*t^6+22*t^8+66*t^10+209*t^12+687*t^14+O(t^16),t,16)</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">;</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">P := 687*t^14+209*t^12+66*t^10+22*t^8+7*t^6+2*t^4+t^2+1;</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">f := 1+(t^4-2*t^2+2)*z+(t^6+3*t^4)*z^2+(8*t^6-4*t^4+6*t^2-2)*z^3+(16*t^6-4*t^4+</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">4*t^2-1)*z^4;</Text-field>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYnLUkjbWlHRiQ2J1EkYW5zRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLyUqcmVmZXJlbmNlR1ElNDA5MUYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSU0MDkwRictSSNtb0dGJDYvUSkmQXNzaWduO0YnL0YzUSdub3JtYWxGJ0Y1RjgvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRkMvJSlzdHJldGNoeUdGQy8lKnN5bW1ldHJpY0dGQy8lKGxhcmdlb3BHRkMvJS5tb3ZhYmxlbGltaXRzR0ZDLyUnYWNjZW50R0ZDLyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGUi1GPDYvUSomdW1pbnVzMDtGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZOL0ZRUSwwLjIyMjIyMjJlbUYnL0ZURlktSSZtZnJhY0dGJDYoLUYjNiYtSSVtc3VwR0YkNiUtRiM2Ji1GLDYnUSdSb290T2ZGJ0YvRjJGNUY4LUY8Nj5RMCZBcHBseUZ1bmN0aW9uO0YnLyUnZmFtaWx5R1EwVGltZXN+TmV3flJvbWFuRicvJSVzaXplR1EjMTJGJy8lJWJvbGRHRkMvRjBGQy8lKnVuZGVybGluZUdGQy8lKnN1YnNjcmlwdEdGQy8lLHN1cGVyc2NyaXB0R0ZDLyUrZm9yZWdyb3VuZEdRKFswLDAsMF1GJy8lK2JhY2tncm91bmRHUS5bMjU1LDI1NSwyNTVdRicvJSdvcGFxdWVHRkMvJStleGVjdXRhYmxlR0ZDLyUpcmVhZG9ubHlHRkMvJSljb21wb3NlZEdGQy8lKmNvbnZlcnRlZEdGQy8lK2ltc2VsZWN0ZWRHRkMvJSxwbGFjZWhvbGRlckdGQy8lNnNlbGVjdGlvbi1wbGFjZWhvbGRlckdGQ0Y/RkFGREZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRGW3ItSShtZmVuY2VkR0YkNiYtRiM2Ki1GIzYmLUZbbzYlLUYsNidRInRGJ0YvRjJGNUY4LUkjbW5HRiQ2JlEiNEYnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJy1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTkZqcUZcci1GW282JS1GLDYnUSNfWkYnRi9GMkY1RjhGaXJGXXNGPy1GPDYvUSgmbWludXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZYRlotRiM2JkZkckZgcy1GW282JUZpcy1GanI2JlEiM0YnRj9GNUY4Rl1zRj8tRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZYRlotRiM2Ji1GXnI2Ji1GIzYmLUZbbzYlRmZyLUZqcjYmUSIyRidGP0Y1RjhGXXNGXHQtRmpyNiZRIjFGJ0Y/RjVGOEY/Rj9GNUY4RmBzRmlzRj9GZnRGZHVGP0Y/RjVGOEY/RmF1Rl1zRlx0Rl1vRj8tRiM2LUZVLUZmbjYoLUYjNiYtRl5yNiYtRiM2Ji1GIzYmLUZecjYmLUYjNiZGZHJGXHRGX3VGP0Y/RjVGOEZgcy1GW282JUZdb0ZjdEZdc0Y/RmZ0LUYjNiZGam5GYHNGX3VGP0Y/Rj9GNUY4RmBzLUZecjYmLUYjNidGVUZdb0ZmdEZkdUY/Rj9GNUY4Rj8tRiM2JkZdb0Zgc0ZfdUY/LyUubGluZXRoaWNrbmVzc0dGZnUvJStkZW5vbWFsaWduR1EnY2VudGVyRicvJSludW1hbGlnbkdGZXcvJSliZXZlbGxlZEdGQ0ZmdEZkdUZmdC1GIzYmLUZecjYmLUYjNidGVUZfdUZmdEZkdUY/Rj9GNUY4RmBzRmd2Rj9GXHRGam5GXHRGXW9GP0Zhd0Zjd0Zmd0Zod0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSRhbnNHRigsJComLCYqJC1JJ1Jvb3RPZkdGJTYjLCoqJkkidEdGKCIiJUkjX1pHRiVGOCIiIiomRjdGOEY5IiIkISIiKiYsJiokRjciIiNGOkY9RjpGOkY5RjpGOkY6RjpGQUY6RjJGPUY6LCwqKiwmKiYsJiokRjdGOEY6RkBGPUY6RjJGPEY6KiZGMkZBRjdGQUY6RjosJkYyRj1GOkY6RjpGMkY9RjchIiNGPUY6RjoqJiwmRkBGPUY6RjpGOkYyRjxGOkYxRj1GMkY9Rj1GPTcjRi4=</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzY2LUkjbWlHRiQ2J1EiVEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZnbi1JJW1zdXBHRiQ2JS1GLDYnUSJ0RidGL0YyRjVGOC1GVjYmUSIyRidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnRlktRiM2JkZfby1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTi9GUVEmMC4wZW1GJy9GVEZfcC1Gam42JUZcby1GVjYmUSI0RidGP0Y1RjhGYm9GP0ZZLUYjNiYtRlY2JlEiN0YnRj9GNUY4RmdvLUZqbjYlRlxvLUZWNiZRIjZGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSMyMkYnRj9GNUY4RmdvLUZqbjYlRlxvLUZWNiZRIjhGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSM2NkYnRj9GNUY4RmdvLUZqbjYlRlxvLUZWNiZRIzEwRidGP0Y1RjhGYm9GP0ZZLUYjNiYtRlY2JlEkMjA5RidGP0Y1RjhGZ28tRmpuNiVGXG8tRlY2JlEjMTJGJ0Y/RjVGOEZib0Y/RlktRiM2Ji1GVjYmUSQ2ODdGJ0Y/RjVGOEZnby1Gam42JUZcby1GVjYmUSMxNEYnRj9GNUY4RmJvRj9GWS1GIzYmLUY8Ni9RIk9GJ0Y/RjVGOEZBRkRGRkZIRkpGTEZORl5wRmBwLUY8Nj5RMCZBcHBseUZ1bmN0aW9uO0YnLyUnZmFtaWx5R1EwVGltZXN+TmV3flJvbWFuRicvJSVzaXplR0Zdcy8lJWJvbGRHRkMvRjBGQy8lKnVuZGVybGluZUdGQy8lKnN1YnNjcmlwdEdGQy8lLHN1cGVyc2NyaXB0R0ZDLyUrZm9yZWdyb3VuZEdRKFswLDAsMF1GJy8lK2JhY2tncm91bmRHUS5bMjU1LDI1NSwyNTVdRicvJSdvcGFxdWVHRkMvJStleGVjdXRhYmxlR0ZDLyUpcmVhZG9ubHlHRkMvJSljb21wb3NlZEdGQy8lKmNvbnZlcnRlZEdGQy8lK2ltc2VsZWN0ZWRHRkMvJSxwbGFjZWhvbGRlckdGQy8lNnNlbGVjdGlvbi1wbGFjZWhvbGRlckdGQ0Y/RkFGREZGRkhGSkZMRk5GXnBGYHAtSShtZmVuY2VkR0YkNiYtRiM2Ji1Gam42JUZcby1GVjYmUSMxNkYnRj9GNUY4RmJvRl51Rmh1Rj9GP0Y1RjhGP0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJUR0YoKzVJInRHRigiIiIiIiFGMCIiI0YyIiIlIiIoIiInIiNBIiIpIiNtIiM1IiQ0IyIjNyIkKG8iIzktSSJPR0YlNiNGMCIjOzcjRi4=</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzY0LUkjbWlHRiQ2J1EiUEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiM2Ji1JI21uR0YkNiZRJDY4N0YnRj9GNUY4LUY8Ni9RMSZJbnZpc2libGVUaW1lcztGJ0Y/L0Y2USUzMTM2RicvRjlRJTMxMzVGJ0ZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURl1vLUklbXN1cEdGJDYlLUYsNidRInRGJ0YvRjJGNUY4LUZYNiZRIzE0RidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnRj8tRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZfcC1GIzYmLUZYNiZRJDIwOUYnRj9GNUY4RmVuLUZgbzYlRmJvLUZYNiZRIzEyRidGP0Y1RjhGaG9GP0ZbcC1GIzYmLUZYNiZRIzY2RidGP0Y1RjhGZW4tRmBvNiVGYm8tRlg2JlEjMTBGJ0Y/RjVGOEZob0Y/RltwLUYjNiYtRlg2JlEjMjJGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSI4RidGP0Y1RjhGaG9GP0ZbcC1GIzYmLUZYNiZRIjdGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSI2RidGP0Y1RjhGaG9GP0ZbcC1GIzYmLUZYNiZRIjJGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSI0RidGP0Y1RjhGaG9GP0ZbcC1GYG82JUZib0Zbc0Zob0ZbcC1GWDYmUSIxRidGP0Y1RjhGPw==">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJQR0YoLDIqJEkidEdGKCIjOSIkKG8qJEYwIiM3IiQ0IyokRjAiIzUiI20qJEYwIiIpIiNBKiRGMCIiJyIiKCokRjAiIiUiIiMqJEYwRkEiIiJGQ0ZDNyNGLg==</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYuLUkjbWlHRiQ2J1EiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZnbi1GIzYmLUkobWZlbmNlZEdGJDYmLUYjNigtSSVtc3VwR0YkNiUtRiw2J1EidEYnRi9GMkY1RjgtRlY2JlEiNEYnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJy1GPDYvUSgmbWludXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZmbkZobi1GIzYmLUZWNiZRIjJGJ0Y/RjVGOC1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTi9GUVEmMC4wZW1GJy9GVEZccS1GYW82JUZjb0ZhcEZpb0Y/RllGYXBGP0Y/RjVGOEZkcC1GLDYnUSJ6RidGL0YyRjVGOEY/RlktRiM2Ji1GXG82Ji1GIzYmLUZhbzYlRmNvLUZWNiZRIjZGJ0Y/RjVGOEZpb0ZZLUYjNiYtRlY2JlEiM0YnRj9GNUY4RmRwRmBvRj9GP0Y/RjVGOEZkcC1GYW82JUZgcUZhcEZpb0Y/RlktRiM2Ji1GXG82Ji1GIzYqLUYjNiYtRlY2JlEiOEYnRj9GNUY4RmRwRmlxRj9GXHAtRiM2JkZmb0ZkcEZgb0Y/RlktRiM2JkZbckZkcEZecUY/RlxwRmFwRj9GP0Y1RjhGZHAtRmFvNiVGYHFGYHJGaW9GP0ZZLUYjNiYtRlxvNiYtRiM2Ki1GIzYmLUZWNiZRIzE2RidGP0Y1RjhGZHBGaXFGP0ZccEZgc0ZZLUYjNiZGZm9GZHBGXnFGP0ZccEZVRj9GP0Y1RjhGZHAtRmFvNiVGYHFGZm9GaW9GP0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJmR0YoLCwiIiJGLyomLCgqJEkidEdGKCIiJUYvKiRGMyIiIyEiI0Y2Ri9GL0kiekdGKEYvRi8qJiwmKiRGMyIiJ0YvRjIiIiRGL0Y4RjZGLyomLCpGOyIiKUYyISIlRjVGPEY3Ri9GL0Y4Rj1GLyomLCpGOyIjO0YyRkFGNUY0ISIiRi9GL0Y4RjRGLzcjRi4=</Equation></Text-field>
</Output>
</Group>
<Group labelreference="L3" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYlLUkjbWlHRiQ2I1EhRicvJStleGVjdXRhYmxlR1EmZmFsc2VGJy8lLG1hdGh2YXJpYW50R1Enbm9ybWFsRic=">JSFH</Equation></Text-field>
</Input>
</Group>
</Worksheet>