<?xml version="1.0" encoding="UTF-8"?>
<Worksheet>
<Version major="2020" minor="0"/>
<Label-Scheme value="2" prefix=""/>
<View-Properties presentation="false" autoexpanding_sections="true" UserProfileName="Maple Default Profile" NumericFormat-ApplyInteger="true" NumericFormat-ApplyRational="true" NumericFormat-ApplyExponent="false" editable="true">
</View-Properties>
<MapleNet-Properties prettyprint="3" warnlevel="3" compactdisplay="false" preplot="" helpbrowser="standard" displayprecision="-1" echo="1" unitattributes="&quot;fontweight&quot; = &quot;bold&quot;" imaginaryunit="I" longdelim="true" elisiontermsthreshold="10000" elisiondigitsafter="100" elisiondigitsbefore="100" plotdevice="inline" errorbreak="1" plotoptions="" plotdriver="opengl" quiet="false" elisiontermsbefore="100" elisiontermsafter="100" historytimestamp="false" screenwidth="79" indentamount="4" plotoutput="terminal" screenpixelheight="1824" rtablesize="[10, 10]" useclientjvm="true" labelwidth="20" postplot="" typesetting="extended" ansi="false" ansicolor="[]" elisiondigitsthreshold="10000" showassumed="1" ansilprint="false" trailingsemicolon="true" errorcursor="false" labelling="true" screenheight="25" prompt="&gt; " verboseproc="1" latexwidth="8.0" ShowLabels="true"/>
<Styles>
<Font name="Heading 1" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Warning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Line Printed Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 2" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="16" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Output" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Inert Output" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[144,144,144]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Heading 3" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="true" opaque="false" readonly="false" size="14" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Diagnostic" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[40,120,40]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 1" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[120,0,14]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text Output" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 2" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 3" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 4" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Ordered List 5" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Header and Footer" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="10" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkError" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Atomic Variable" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[175,0,175]" italic="true" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="HyperlinkWarning" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[0,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Dictionary Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[147,0,15]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="2D Math" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Bullet Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Plot" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Annotation Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="List Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Dash Item" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="2D Input" background="[255,255,255]" bold="false" executable="true" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Error" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,255]" italic="false" opaque="false" readonly="true" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Title" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="18" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Text" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Normal" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Caption Reference" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Code" background="[255,255,255]" bold="false" executable="false" family="Courier New" foreground="[255,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Maple Input Placeholder" background="[255,255,255]" bold="true" executable="true" family="Courier New" foreground="[200,0,200]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="true"/>
<Font name="Equation Label" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Author" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Font name="Hyperlink" background="[255,255,255]" bold="false" executable="false" family="Times New Roman" foreground="[0,128,128]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="true" placeholder="false"/>
<Font name="Caption Text" background="[255,255,255]" bold="true" executable="false" family="Times New Roman" foreground="[0,0,0]" italic="false" opaque="false" readonly="false" size="12" subscript="false" superscript="false" underline="false" placeholder="false"/>
<Layout name="Heading 1" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="4" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Warning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 4" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Line Printed Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 2" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="2" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Output" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.3" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Heading 3" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Diagnostic" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="any" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 1" alignment="left" bullet="numeric" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Text Output" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="newline" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Ordered List 2" alignment="left" bullet="alphabetic" firstindent="0" leftmargin="36" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 3" alignment="left" bullet="roman" firstindent="0" leftmargin="72" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 4" alignment="left" bullet="ALPHABETIC" firstindent="0" leftmargin="108" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Ordered List 5" alignment="left" bullet="ROMAN" firstindent="0" leftmargin="144" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="-1" bulletsuffix="."/>
<Layout name="Annotation Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkError" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="HyperlinkWarning" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Bullet Item" alignment="left" bullet="dot" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Maple Plot" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="List Item" alignment="left" bullet="indent" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Dash Item" alignment="left" bullet="dash" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="3" spacebelow="3" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Error" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Title" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="12" spacebelow="12" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Normal" alignment="left" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="0" spacebelow="0" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Layout name="Author" alignment="centred" bullet="none" firstindent="0" leftmargin="0" rightmargin="0" linespacing="0.0" spaceabove="8" spacebelow="8" linebreak="space" pagebreak-before="false" initial="0" bulletsuffix=""/>
<Pencil-style name="Pencil 1" pen-color="[0,0,0]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 2" pen-color="[0,0,255]" pen-height="1.0" pen-width="1.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 3" pen-color="[0,0,0]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 4" pen-color="[0,0,255]" pen-height="3.0" pen-width="3.0" pen-opacity="1.0"/>
<Pencil-style name="Pencil 5" pen-color="[255,0,0]" pen-height="5.0" pen-width="5.0" pen-opacity="1.0"/>
<Highlighter-style name="Highlighter 5" pen-color="[255,255,0]" pen-height="48.0" pen-width="48.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 3" pen-color="[51,255,0]" pen-height="24.0" pen-width="24.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 4" pen-color="[0,255,255]" pen-height="32.0" pen-width="32.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 1" pen-color="[255,153,255]" pen-height="12.0" pen-width="8.0" pen-opacity="0.8"/>
<Highlighter-style name="Highlighter 2" pen-color="[255,204,0]" pen-height="14.0" pen-width="14.0" pen-opacity="0.8"/>
</Styles>
<Startup-Code startupcode=""/>
<Task-table>
    <Task-category name="&lt;default&gt;"/>
</Task-table>
<Task/>
<Group hide-input="false" labelreference="L2" drawlabel="true" applyint="true" applyrational="true" applyexponent="false"><Text-field prompt="&gt; " style="Maple Input" layout="Normal">ans := -RootOf(_Z^3*t^3-_Z+1)/(RootOf(_Z^3*t^3-_Z+1)-2);</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">T := series(1+2*t^3+8*t^6+38*t^9+196*t^12+1062*t^15+5948*t^18+O(t^20),t,20);</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">P := 5948*t^18+1062*t^15+196*t^12+38*t^9+8*t^6+2*t^3+1;</Text-field><Text-field prompt="&gt; " style="Maple Input" layout="Normal">f := 1+z-z^2+(8*t^3-1)*z^3;</Text-field>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYnLUkjbWlHRiQ2J1EkYW5zRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLyUqcmVmZXJlbmNlR1ElNDA5MUYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSU0MDkwRictSSNtb0dGJDYvUSkmQXNzaWduO0YnL0YzUSdub3JtYWxGJ0Y1RjgvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRkMvJSlzdHJldGNoeUdGQy8lKnN5bW1ldHJpY0dGQy8lKGxhcmdlb3BHRkMvJS5tb3ZhYmxlbGltaXRzR0ZDLyUnYWNjZW50R0ZDLyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGUi1GPDYvUSomdW1pbnVzMDtGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZOL0ZRUSwwLjIyMjIyMjJlbUYnL0ZURlktSSZtZnJhY0dGJDYoLUYjNiYtRiw2J1EnUm9vdE9mRidGL0YyRjVGOC1GPDY+UTAmQXBwbHlGdW5jdGlvbjtGJy8lJ2ZhbWlseUdRMFRpbWVzfk5ld35Sb21hbkYnLyUlc2l6ZUdRIzEyRicvJSVib2xkR0ZDL0YwRkMvJSp1bmRlcmxpbmVHRkMvJSpzdWJzY3JpcHRHRkMvJSxzdXBlcnNjcmlwdEdGQy8lK2ZvcmVncm91bmRHUShbMCwwLDBdRicvJStiYWNrZ3JvdW5kR1EuWzI1NSwyNTUsMjU1XUYnLyUnb3BhcXVlR0ZDLyUrZXhlY3V0YWJsZUdGQy8lKXJlYWRvbmx5R0ZDLyUpY29tcG9zZWRHRkMvJSpjb252ZXJ0ZWRHRkMvJStpbXNlbGVjdGVkR0ZDLyUscGxhY2Vob2xkZXJHRkMvJTZzZWxlY3Rpb24tcGxhY2Vob2xkZXJHRkNGP0ZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURmZxLUkobWZlbmNlZEdGJDYmLUYjNigtRiM2Ji1JJW1zdXBHRiQ2JS1GLDYnUSNfWkYnRi9GMkY1RjgtSSNtbkdGJDYmUSIzRidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnLUY8Ni9RMSZJbnZpc2libGVUaW1lcztGJ0Y/L0Y2USUzMTM2RicvRjlRJTMxMzVGJ0ZBRkRGRkZIRkpGTEZORmVxRmdxLUZgcjYlLUYsNidRInRGJ0YvRjJGNUY4RmVyRmlyRj8tRjw2L1EoJm1pbnVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk5GWEZaRmJyLUY8Ni9RJyZwbHVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk5GWEZaLUZmcjYmUSIxRidGP0Y1RjhGP0Y/RjVGOEY/LUYjNiZGaG5GaHMtRmZyNiZRIjJGJ0Y/RjVGOEY/LyUubGluZXRoaWNrbmVzc0dGYHQvJStkZW5vbWFsaWduR1EnY2VudGVyRicvJSludW1hbGlnbkdGanQvJSliZXZlbGxlZEdGQ0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSRhbnNHRigsJComLUknUm9vdE9mR0YlNiMsKComSSNfWkdGJSIiJEkidEdGKEY2IiIiRjUhIiJGOEY4RjgsJkYwRjghIiNGOEY5Rjk3I0Yu</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzY0LUkjbWlHRiQ2J1EiVEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZnbi1GIzYmLUZWNiZRIjJGJ0Y/RjVGOC1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTi9GUVEmMC4wZW1GJy9GVEZmby1JJW1zdXBHRiQ2JS1GLDYnUSJ0RidGL0YyRjVGOC1GVjYmUSIzRidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnRj9GWS1GIzYmLUZWNiZRIjhGJ0Y/RjVGOEZeby1GaW82JUZbcC1GVjYmUSI2RidGP0Y1RjhGYXBGP0ZZLUYjNiYtRlY2JlEjMzhGJ0Y/RjVGOEZeby1GaW82JUZbcC1GVjYmUSI5RidGP0Y1RjhGYXBGP0ZZLUYjNiYtRlY2JlEkMTk2RidGP0Y1RjhGXm8tRmlvNiVGW3AtRlY2JlEjMTJGJ0Y/RjVGOEZhcEY/RlktRiM2Ji1GVjYmUSUxMDYyRidGP0Y1RjhGXm8tRmlvNiVGW3AtRlY2JlEjMTVGJ0Y/RjVGOEZhcEY/RlktRiM2Ji1GVjYmUSU1OTQ4RidGP0Y1RjhGXm8tRmlvNiVGW3AtRlY2JlEjMThGJ0Y/RjVGOEZhcEY/RlktRiM2Ji1GPDYvUSJPRidGP0Y1RjhGQUZERkZGSEZKRkxGTkZlb0Znby1GPDY+UTAmQXBwbHlGdW5jdGlvbjtGJy8lJ2ZhbWlseUdRMFRpbWVzfk5ld35Sb21hbkYnLyUlc2l6ZUdGYXIvJSVib2xkR0ZDL0YwRkMvJSp1bmRlcmxpbmVHRkMvJSpzdWJzY3JpcHRHRkMvJSxzdXBlcnNjcmlwdEdGQy8lK2ZvcmVncm91bmRHUShbMCwwLDBdRicvJStiYWNrZ3JvdW5kR1EuWzI1NSwyNTUsMjU1XUYnLyUnb3BhcXVlR0ZDLyUrZXhlY3V0YWJsZUdGQy8lKXJlYWRvbmx5R0ZDLyUpY29tcG9zZWRHRkMvJSpjb252ZXJ0ZWRHRkMvJStpbXNlbGVjdGVkR0ZDLyUscGxhY2Vob2xkZXJHRkMvJTZzZWxlY3Rpb24tcGxhY2Vob2xkZXJHRkNGP0ZBRkRGRkZIRkpGTEZORmVvRmdvLUkobWZlbmNlZEdGJDYmLUYjNiYtRmlvNiVGW3AtRlY2JlEjMjBGJ0Y/RjVGOEZhcEZcdUZmdUY/Rj9GNUY4Rj9GPw==">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJUR0YoKzNJInRHRigiIiIiIiEiIiMiIiQiIikiIiciI1EiIioiJCc+IiM3IiVpNSIjOiIlW2YiIz0tSSJPR0YlNiNGMCIjPzcjRi4=</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYyLUkjbWlHRiQ2J1EiUEYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItRiM2Ji1JI21uR0YkNiZRJTU5NDhGJ0Y/RjVGOC1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTi9GUVEmMC4wZW1GJy9GVEZdby1JJW1zdXBHRiQ2JS1GLDYnUSJ0RidGL0YyRjVGOC1GWDYmUSMxOEYnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJ0Y/LUY8Ni9RJyZwbHVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk4vRlFRLDAuMjIyMjIyMmVtRicvRlRGX3AtRiM2Ji1GWDYmUSUxMDYyRidGP0Y1RjhGZW4tRmBvNiVGYm8tRlg2JlEjMTVGJ0Y/RjVGOEZob0Y/RltwLUYjNiYtRlg2JlEkMTk2RidGP0Y1RjhGZW4tRmBvNiVGYm8tRlg2JlEjMTJGJ0Y/RjVGOEZob0Y/RltwLUYjNiYtRlg2JlEjMzhGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSI5RidGP0Y1RjhGaG9GP0ZbcC1GIzYmLUZYNiZRIjhGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSI2RidGP0Y1RjhGaG9GP0ZbcC1GIzYmLUZYNiZRIjJGJ0Y/RjVGOEZlbi1GYG82JUZiby1GWDYmUSIzRidGP0Y1RjhGaG9GP0ZbcC1GWDYmUSIxRidGP0Y1RjhGPw==">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJQR0YoLDAqJEkidEdGKCIjPSIlW2YqJEYwIiM6IiVpNSokRjAiIzciJCc+KiRGMCIiKiIjUSokRjAiIiciIikqJEYwIiIkIiIjIiIiRkI3I0Yu</Equation></Text-field>
</Output>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYsLUkjbWlHRiQ2J1EiZkYnLyUnaXRhbGljR1EldHJ1ZUYnLyUsbWF0aHZhcmlhbnRHUSdpdGFsaWNGJy8lKnJlZmVyZW5jZUdRJTQwOTFGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElNDA5MEYnLUkjbW9HRiQ2L1EpJkFzc2lnbjtGJy9GM1Enbm9ybWFsRidGNUY4LyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRLDAuMjc3Nzc3OGVtRicvJSdyc3BhY2VHRlItSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EnJnBsdXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTi9GUVEsMC4yMjIyMjIyZW1GJy9GVEZnbi1GLDYnUSJ6RidGL0YyRjVGOC1GPDYvUSgmbWludXM7RidGP0Y1RjhGQUZERkZGSEZKRkxGTkZmbkZobi1JJW1zdXBHRiQ2JUZpbi1GVjYmUSIyRidGP0Y1RjgvJTFzdXBlcnNjcmlwdHNoaWZ0R1EiMEYnRlktRiM2Ji1JKG1mZW5jZWRHRiQ2Ji1GIzYmLUYjNiYtRlY2JlEiOEYnRj9GNUY4LUY8Ni9RMSZJbnZpc2libGVUaW1lcztGJ0Y/L0Y2USUzMTM2RicvRjlRJTMxMzVGJ0ZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURlxxLUZgbzYlLUYsNidRInRGJ0YvRjJGNUY4LUZWNiZRIjNGJ0Y/RjVGOEZlb0Y/RlxvRlVGP0Y/RjVGOEZkcC1GYG82JUZpbkZjcUZlb0Y/Rj8=">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSJmR0YoLCoiIiJGL0kiekdGKEYvKiRGMCIiIyEiIiomLCYqJEkidEdGKCIiJCIiKUYzRi9GL0YwRjhGLzcjRi4=</Equation></Text-field>
</Output>
</Group>
<Group hide-input="false" labelreference="L3" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEkY2ZzRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLUkjbW9HRiQ2L1EifkYnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRJjAuMGVtRicvJSdyc3BhY2VHRlItRjY2LVEqJmNvbG9uZXE7RidGOUZBRkRGRkZIRkpGTEZOL0ZRUSwwLjI3Nzc3NzhlbUYnL0ZURlktSShtZmVuY2VkR0YkNiYtRiM2Ji1GLDYlUSdjb2VmZnNGJ0YvRjItRmZuNiQtRiM2Ky1GLDYlUSJmRidGL0YyLUY2Ni1RIixGJ0Y5RkEvRkVGMUZGRkhGSkZMRk5GUC9GVFEsMC4zMzMzMzMzZW1GJy1GLDYlUSJ6RidGL0YyRmRvLUY2Ni1RIidGJ0Y5RkFGREZGRkhGSkZMRk4vRlFRLDAuMTExMTExMWVtRidGUy1GLDYlUSN6dkYnRi9GMkZdcC8lK2V4ZWN1dGFibGVHRkNGOUY5RmVwRjlGOS8lJW9wZW5HUSJbRicvJSZjbG9zZUdRIl1GJ0ZlcEY5">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEkY2ZzRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLUkjbW9HRiQ2L1EifkYnL0YzUSdub3JtYWxGJy8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0ZDLyUpc3RyZXRjaHlHRkMvJSpzeW1tZXRyaWNHRkMvJShsYXJnZW9wR0ZDLyUubW92YWJsZWxpbWl0c0dGQy8lJ2FjY2VudEdGQy8lJ2xzcGFjZUdRJjAuMGVtRicvJSdyc3BhY2VHRlItRjY2LVEqJmNvbG9uZXE7RidGOUZBRkRGRkZIRkpGTEZOL0ZRUSwwLjI3Nzc3NzhlbUYnL0ZURlktSShtZmVuY2VkR0YkNiYtRiM2Ji1GLDYlUSdjb2VmZnNGJ0YvRjItRmZuNiQtRiM2Ky1GLDYlUSJmRidGL0YyLUY2Ni1RIixGJ0Y5RkEvRkVGMUZGRkhGSkZMRk5GUC9GVFEsMC4zMzMzMzMzZW1GJy1GLDYlUSJ6RidGL0YyRmRvLUY2Ni1RIidGJ0Y5RkFGREZGRkhGSkZMRk4vRlFRLDAuMTExMTExMWVtRidGUy1GLDYlUSN6dkYnRi9GMkZdcC8lK2V4ZWN1dGFibGVHRkNGOUY5RmVwRjlGOS8lJW9wZW5HUSJbRicvJSZjbG9zZUdRIl1GJ0ZlcEY5</Equation></Text-field>
</Input>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbWlHRiQ2J1EkY2ZzRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLyUqcmVmZXJlbmNlR1ElNDA5MUYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSU0MDkwRictSSNtb0dGJDYvUSkmQXNzaWduO0YnL0YzUSdub3JtYWxGJ0Y1RjgvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRkMvJSlzdHJldGNoeUdGQy8lKnN5bW1ldHJpY0dGQy8lKGxhcmdlb3BHRkMvJS5tb3ZhYmxlbGltaXRzR0ZDLyUnYWNjZW50R0ZDLyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGUi1JKG1mZW5jZWRHRiQ2KC1GIzYsLUkjbW5HRiQ2JlEiMUYnRj9GNUY4LUY8Ni9RIixGJ0Y/RjVGOEZBL0ZFRjFGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZUUSwwLjMzMzMzMzNlbUYnRlpGaG4tRmVuNiZRKyZ1bWludXMwOzFGJ0Y/RjVGOEZobi1GIzYmLUYjNiYtRmVuNiZRIjhGJ0Y/RjVGOC1GPDYvUTEmSW52aXNpYmxlVGltZXM7RidGPy9GNlElMzEzNkYnL0Y5USUzMTM1RidGQUZERkZGSEZKRkxGTkZcby9GVEZdby1JJW1zdXBHRiQ2JS1GLDYnUSJ0RidGL0YyRjVGOC1GZW42JlEiM0YnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJ0Y/LUY8Ni9RKCZtaW51cztGJ0Y/RjVGOEZBRkRGRkZIRkpGTEZOL0ZRUSwwLjIyMjIyMjJlbUYnL0ZURmJxRlpGPy8lK2ZvcmVncm91bmRHUShbMCwwLDBdRicvJSlyZWFkb25seUdGQ0Y/Rj9GNUY4LyUlb3BlbkdRJyZsc3FiO0YnLyUmY2xvc2VHUScmcnNxYjtGJ0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSRjZnNHRig3JiIiIkYvISIiLCYqJEkidEdGKCIiJCIiKUYwRi83I0Yu</Equation></Text-field>
</Output>
</Group>
<Group hide-input="false" labelreference="L4" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEjenZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRictSSNtb0dGJDYvUSomY29sb25lcTtGJy9GM1Enbm9ybWFsRicvJSpyZWZlcmVuY2VHUSUyMzI1RicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTIzMjRGJy8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGQy8lKXN0cmV0Y2h5R0ZDLyUqc3ltbWV0cmljR0ZDLyUobGFyZ2VvcEdGQy8lLm1vdmFibGVsaW1pdHNHRkMvJSdhY2NlbnRHRkMvJSdsc3BhY2VHUSwwLjI3Nzc3NzhlbUYnLyUncnNwYWNlR0ZSLUY2Ni9RIn5GJ0Y5RjtGPkZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURlktSShtZmVuY2VkR0YkNiYtRiM2JUYrLyUrZXhlY3V0YWJsZUdGQ0Y5RjkvJSVvcGVuR1EiW0YnLyUmY2xvc2VHUSJdRidGam5GOQ==">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEjenZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRictSSNtb0dGJDYvUSomY29sb25lcTtGJy9GM1Enbm9ybWFsRicvJSpyZWZlcmVuY2VHUSUyMzI1RicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTIzMjRGJy8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGQy8lKXN0cmV0Y2h5R0ZDLyUqc3ltbWV0cmljR0ZDLyUobGFyZ2VvcEdGQy8lLm1vdmFibGVsaW1pdHNHRkMvJSdhY2NlbnRHRkMvJSdsc3BhY2VHUSwwLjI3Nzc3NzhlbUYnLyUncnNwYWNlR0ZSLUY2Ni9RIn5GJ0Y5RjtGPkZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURlktSShtZmVuY2VkR0YkNiYtRiM2JUYrLyUrZXhlY3V0YWJsZUdGQ0Y5RjkvJSVvcGVuR1EiW0YnLyUmY2xvc2VHUSJdRidGam5GOQ==</Equation></Text-field>
</Input>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbWlHRiQ2J1EjenZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRicvJSpyZWZlcmVuY2VHUSU0MDkxRicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTQwOTBGJy1JI21vR0YkNi9RKSZBc3NpZ247RicvRjNRJ25vcm1hbEYnRjVGOC8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGQy8lKXN0cmV0Y2h5R0ZDLyUqc3ltbWV0cmljR0ZDLyUobGFyZ2VvcEdGQy8lLm1vdmFibGVsaW1pdHNHRkMvJSdhY2NlbnRHRkMvJSdsc3BhY2VHUSwwLjI3Nzc3NzhlbUYnLyUncnNwYWNlR0ZSLUkobWZlbmNlZEdGJDYoLUYjNiwtSSNtbkdGJDYmUSIxRidGP0Y1RjgtRjw2L1EiLEYnRj9GNUY4RkEvRkVGMUZGRkhGSkZMRk4vRlFRJjAuMGVtRicvRlRRLDAuMzMzMzMzM2VtRictRiw2J1EiekYnRi9GMkY1RjhGaG4tSSVtc3VwR0YkNiVGYG8tRmVuNiZRIjJGJ0Y/RjVGOC8lMXN1cGVyc2NyaXB0c2hpZnRHUSIwRidGaG4tRmRvNiVGYG8tRmVuNiZRIjNGJ0Y/RjVGOEZpby8lK2ZvcmVncm91bmRHUShbMCwwLDBdRicvJSlyZWFkb25seUdGQ0Y/Rj9GNUY4LyUlb3BlbkdRJyZsc3FiO0YnLyUmY2xvc2VHUScmcnNxYjtGJ0Y/">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSN6dkdGKDcmIiIiSSJ6R0YoKiRGMCIiIyokRjAiIiQ3I0Yu</Equation></Text-field>
</Output>
</Group>
<Group hide-input="false" labelreference="L5" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbWlHRiQ2JVEkemlwRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLUkobWZlbmNlZEdGJDYkLUYjNistRjY2JC1GIzYnLUYsNiVRImFGJ0YvRjItSSNtb0dGJDYtUSIsRicvRjNRJ25vcm1hbEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0YxLyUpc3RyZXRjaHlHRkkvJSpzeW1tZXRyaWNHRkkvJShsYXJnZW9wR0ZJLyUubW92YWJsZWxpbWl0c0dGSS8lJ2FjY2VudEdGSS8lJ2xzcGFjZUdRJjAuMGVtRicvJSdyc3BhY2VHUSwwLjMzMzMzMzNlbUYnLUYsNiVRImJGJ0YvRjIvJStleGVjdXRhYmxlR0ZJRkVGRS1GQjYvUSgmc3JhcnI7RidGRS8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnRkcvRktGSUZMRk5GUEZSRlRGVi9GWkZYLUY2NiZGPEZFLyUlb3BlbkdRIltGJy8lJmNsb3NlR1EiXUYnRkEtRjY2Ji1GIzYnLUkjbW5HRiQ2JFEiMUYnRkVGQS1GY3A2JFEiMkYnRkVGaW5GRUZFRmhvRltwRkEtRjY2Ji1GIzYnLUZjcDYkUSIzRidGRUZBLUZjcDYkUSI0RidGRUZpbkZFRkVGaG9GW3BGaW5GRUZFRmluRkU=">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbWlHRiQ2JVEkemlwRicvJSdpdGFsaWNHUSV0cnVlRicvJSxtYXRodmFyaWFudEdRJ2l0YWxpY0YnLUkobWZlbmNlZEdGJDYkLUYjNistRjY2JC1GIzYnLUYsNiVRImFGJ0YvRjItSSNtb0dGJDYtUSIsRicvRjNRJ25vcm1hbEYnLyUmZmVuY2VHUSZmYWxzZUYnLyUqc2VwYXJhdG9yR0YxLyUpc3RyZXRjaHlHRkkvJSpzeW1tZXRyaWNHRkkvJShsYXJnZW9wR0ZJLyUubW92YWJsZWxpbWl0c0dGSS8lJ2FjY2VudEdGSS8lJ2xzcGFjZUdRJjAuMGVtRicvJSdyc3BhY2VHUSwwLjMzMzMzMzNlbUYnLUYsNiVRImJGJ0YvRjIvJStleGVjdXRhYmxlR0ZJRkVGRS1GQjYvUSgmc3JhcnI7RidGRS8lKnJlZmVyZW5jZUdRJTIzMjVGJy8lMmRpc3BsYXlfcmVmZXJlbmNlR1ElMjMyNEYnRkcvRktGSUZMRk5GUEZSRlRGVi9GWkZYLUY2NiZGPEZFLyUlb3BlbkdRIltGJy8lJmNsb3NlR1EiXUYnRkEtRjY2Ji1GIzYnLUkjbW5HRiQ2JFEiMUYnRkVGQS1GY3A2JFEiMkYnRkVGaW5GRUZFRmhvRltwRkEtRjY2Ji1GIzYnLUZjcDYkUSIzRidGRUZBLUZjcDYkUSI0RidGRUZpbkZFRkVGaG9GW3BGaW5GRUZFRmluRkU=</Equation></Text-field>
</Input>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUkobWZlbmNlZEc2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUklbXJvd0dGJDYoLUYjNigtRiw2KC1JI21uR0YkNiZRIjFGJy8lLG1hdGh2YXJpYW50R1Enbm9ybWFsRicvJSpyZWZlcmVuY2VHUSU0MDkxRicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTQwOTBGJy1JI21vR0YkNi9RIixGJ0Y2RjlGPC8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdRJXRydWVGJy8lKXN0cmV0Y2h5R0ZFLyUqc3ltbWV0cmljR0ZFLyUobGFyZ2VvcEdGRS8lLm1vdmFibGVsaW1pdHNHRkUvJSdhY2NlbnRHRkUvJSdsc3BhY2VHUSYwLjBlbUYnLyUncnNwYWNlR1EsMC4zMzMzMzMzZW1GJy1GMzYmUSIzRidGNkY5RjwvJStmb3JlZ3JvdW5kR1EoWzAsMCwwXUYnLyUpcmVhZG9ubHlHRkVGNkY2RjlGPC8lJW9wZW5HUScmbHNxYjtGJy8lJmNsb3NlR1EnJnJzcWI7RidGPy1GIzYoLUYsNigtRjM2JlEiMkYnRjZGOUY8Rj8tRjM2JlEiNEYnRjZGOUY8RmZuRmluRjZGNkY5RjxGW29GXm9GZm5GaW5GNkY2RjlGPEZbb0Zebw==">NyQ3JCIiIiIiJDckIiIjIiIl</Equation></Text-field>
</Output>
</Group>
<Group hide-input="false" labelreference="L6" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEjZmZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRictSSNtb0dGJDYtUSomY29sb25lcTtGJy9GM1Enbm9ybWFsRicvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRj0vJSlzdHJldGNoeUdGPS8lKnN5bW1ldHJpY0dGPS8lKGxhcmdlb3BHRj0vJS5tb3ZhYmxlbGltaXRzR0Y9LyUnYWNjZW50R0Y9LyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGTC1GLDYlUSRhZGRGJ0YvRjItSShtZmVuY2VkR0YkNiQtRiM2Ji1GLDYlUSR6aXBGJ0YvRjItRlM2JC1GIzYxLUZTNiQtRiM2Jy1GLDYlUSJhRidGL0YyLUY2Ni1RIixGJ0Y5RjsvRj9GMUZARkJGREZGRkgvRktRJjAuMGVtRicvRk5RLDAuMzMzMzMzM2VtRictRiw2JVEiYkYnRi9GMi8lK2V4ZWN1dGFibGVHRj1GOUY5LUY2Ni9RKCZzcmFycjtGJ0Y5LyUqcmVmZXJlbmNlR1ElMjMyNUYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSUyMzI0RidGO0Y+RkBGQkZERkZGSEZjby9GTkZkby1GLDYlUSdmYWN0b3JGJ0YvRjItRlM2JC1GIzYlRlxvRmpvRjlGOS1GNjYvUScmc2RvdDtGJ0Y5Rl9wRmJwRjtGPkZARkJGREZGRkhGY29GZXBGZ29GX28tRjY2L1EifkYnRjlGX3BGYnBGO0Y+RkBGQkZERkZGSEZjb0ZlcEZgcS1GLDYlUSRjZnNGJ0YvRjJGX29GYHEtRiw2JVEjenZGJ0YvRjJGam9GOUY5RmpvRjlGOUZqb0Y5">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYoLUkjbWlHRiQ2JVEjZmZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRictSSNtb0dGJDYtUSomY29sb25lcTtGJy9GM1Enbm9ybWFsRicvJSZmZW5jZUdRJmZhbHNlRicvJSpzZXBhcmF0b3JHRj0vJSlzdHJldGNoeUdGPS8lKnN5bW1ldHJpY0dGPS8lKGxhcmdlb3BHRj0vJS5tb3ZhYmxlbGltaXRzR0Y9LyUnYWNjZW50R0Y9LyUnbHNwYWNlR1EsMC4yNzc3Nzc4ZW1GJy8lJ3JzcGFjZUdGTC1GLDYlUSRhZGRGJ0YvRjItSShtZmVuY2VkR0YkNiQtRiM2Ji1GLDYlUSR6aXBGJ0YvRjItRlM2JC1GIzYxLUZTNiQtRiM2Jy1GLDYlUSJhRidGL0YyLUY2Ni1RIixGJ0Y5RjsvRj9GMUZARkJGREZGRkgvRktRJjAuMGVtRicvRk5RLDAuMzMzMzMzM2VtRictRiw2JVEiYkYnRi9GMi8lK2V4ZWN1dGFibGVHRj1GOUY5LUY2Ni9RKCZzcmFycjtGJ0Y5LyUqcmVmZXJlbmNlR1ElMjMyNUYnLyUyZGlzcGxheV9yZWZlcmVuY2VHUSUyMzI0RidGO0Y+RkBGQkZERkZGSEZjby9GTkZkby1GLDYlUSdmYWN0b3JGJ0YvRjItRlM2JC1GIzYlRlxvRmpvRjlGOS1GNjYvUScmc2RvdDtGJ0Y5Rl9wRmJwRjtGPkZARkJGREZGRkhGY29GZXBGZ29GX28tRjY2L1EifkYnRjlGX3BGYnBGO0Y+RkBGQkZERkZGSEZjb0ZlcEZgcS1GLDYlUSRjZnNGJ0YvRjJGX29GYHEtRiw2JVEjenZGJ0YvRjJGam9GOUY5RmpvRjlGOUZqb0Y5</Equation></Text-field>
</Input>
<Output><Text-field style="2D Output" layout="Maple Output"><Equation executable="false" style="2D Output" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYsLUkjbWlHRiQ2J1EjZmZGJy8lJ2l0YWxpY0dRJXRydWVGJy8lLG1hdGh2YXJpYW50R1EnaXRhbGljRicvJSpyZWZlcmVuY2VHUSU0MDkxRicvJTJkaXNwbGF5X3JlZmVyZW5jZUdRJTQwOTBGJy1JI21vR0YkNi9RKSZBc3NpZ247RicvRjNRJ25vcm1hbEYnRjVGOC8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGQy8lKXN0cmV0Y2h5R0ZDLyUqc3ltbWV0cmljR0ZDLyUobGFyZ2VvcEdGQy8lLm1vdmFibGVsaW1pdHNHRkMvJSdhY2NlbnRHRkMvJSdsc3BhY2VHUSwwLjI3Nzc3NzhlbUYnLyUncnNwYWNlR0ZSLUkjbW5HRiQ2JlEiMUYnRj9GNUY4LUY8Ni9RJyZwbHVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk4vRlFRLDAuMjIyMjIyMmVtRicvRlRGZ24tRiw2J1EiekYnRi9GMkY1RjgtRjw2L1EoJm1pbnVzO0YnRj9GNUY4RkFGREZGRkhGSkZMRk5GZm5GaG4tSSVtc3VwR0YkNiVGaW4tRlY2JlEiMkYnRj9GNUY4LyUxc3VwZXJzY3JpcHRzaGlmdEdRIjBGJ0ZZLUYjNigtSShtZmVuY2VkR0YkNiYtRiM2Ji1GIzYmRmJvLUY8Ni9RMSZJbnZpc2libGVUaW1lcztGJ0Y/L0Y2USUzMTM2RicvRjlRJTMxMzVGJ0ZBRkRGRkZIRkpGTEZOL0ZRUSYwLjBlbUYnL0ZURmlwLUYsNidRInRGJ0YvRjJGNUY4Rj9GXG9GVUY/Rj9GNUY4RmFwLUZbcDYmLUYjNigtRiM2Ji1GVjYmUSI0RidGP0Y1RjhGYXAtRmBvNiVGW3FGYm9GZW9GP0ZZRl9wRllGVUY/Rj9GNUY4RmFwLUZgbzYlRmluLUZWNiZRIjNGJ0Y/RjVGOEZlb0Y/Rj8=">LV9JLFR5cGVzZXR0aW5nRzYkJSpwcm90ZWN0ZWRHSShfc3lzbGliRzYiSSxtcHJpbnRzbGFzaEdGKDYkNyM+SSNmZkdGKCwqIiIiRi9JInpHRihGLyokRjAiIiMhIiIqKCwmSSJ0R0YoRjJGM0YvRi8sKCokRjZGMiIiJUY2RjJGL0YvRi9GMCIiJEYvNyNGLg==</Equation></Text-field>
</Output>
</Group>
<Group labelreference="L7" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbW9HRiQ2LVEiP0YnLyUsbWF0aHZhcmlhbnRHUSdub3JtYWxGJy8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGNC8lKXN0cmV0Y2h5R0Y0LyUqc3ltbWV0cmljR0Y0LyUobGFyZ2VvcEdGNC8lLm1vdmFibGVsaW1pdHNHRjQvJSdhY2NlbnRHRjQvJSdsc3BhY2VHUSwwLjExMTExMTFlbUYnLyUncnNwYWNlR0ZDLUkjbWlHRiQ2JVEkc3VtRicvJSdpdGFsaWNHUSV0cnVlRicvRjBRJ2l0YWxpY0YnLyUrZXhlY3V0YWJsZUdGNEYv">LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYmLUkjbW9HRiQ2LVEiP0YnLyUsbWF0aHZhcmlhbnRHUSdub3JtYWxGJy8lJmZlbmNlR1EmZmFsc2VGJy8lKnNlcGFyYXRvckdGNC8lKXN0cmV0Y2h5R0Y0LyUqc3ltbWV0cmljR0Y0LyUobGFyZ2VvcEdGNC8lLm1vdmFibGVsaW1pdHNHRjQvJSdhY2NlbnRHRjQvJSdsc3BhY2VHUSwwLjExMTExMTFlbUYnLyUncnNwYWNlR0ZDLUkjbWlHRiQ2JVEkc3VtRicvJSdpdGFsaWNHUSV0cnVlRicvRjBRJ2l0YWxpY0YnLyUrZXhlY3V0YWJsZUdGNEYv</Equation></Text-field>
</Input>
</Group>
<Group labelreference="L8" drawlabel="true" applyint="true" applyrational="true" applyexponent="false">
<Input><Text-field prompt="&gt; " style="Maple Input" layout="Normal"><Equation executable="true" style="2D Input" input-equation="" display="LUklbXJvd0c2Iy9JK21vZHVsZW5hbWVHNiJJLFR5cGVzZXR0aW5nR0koX3N5c2xpYkdGJzYlLUkjbWlHRiQ2I1EhRicvJStleGVjdXRhYmxlR1EmZmFsc2VGJy8lLG1hdGh2YXJpYW50R1Enbm9ybWFsRic=">JSFH</Equation></Text-field>
</Input>
</Group>
</Worksheet>